
(function(){
'use strict';
const RESTAURANT={address:'Real Estates Covai, 9/102, Periyar Nagar, Civil Aero Post, Coimbatore, Tamil Nadu 641048',lat:11.051992,lng:77.0427325};
let app,auth,db,user=null,adminOk=false,orders=[],riders=[],store={},filter='active';
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
function money(v){return '₹'+Math.round(Number(v||0))} function clean(v){return String(v??'').trim()} function phone10(v){let d=clean(v).replace(/\D/g,'');return d.length>10?d.slice(-10):d}
function ts(v){if(!v)return null;if(typeof v.toDate==='function')return v.toDate();if(v.seconds)return new Date(v.seconds*1000);let d=new Date(v);return isNaN(d)?null:d}
function now(){return firebase.firestore.FieldValue.serverTimestamp()} function setNotice(msg){const n=$('#notice');n.hidden=!msg;n.textContent=msg||''}
function init(){if(!window.firebase||!window.TIFFIN_FIREBASE_CONFIG){setNotice('Firebase config missing');return}firebase.initializeApp(window.TIFFIN_FIREBASE_CONFIG);auth=firebase.auth();db=firebase.firestore();bind();auth.onAuthStateChanged(onAuth)}
function bind(){ $('#loginBtn').onclick=login; $('#logoutBtn').onclick=()=>auth.signOut(); $('#refreshBtn').onclick=()=>location.reload(); $('#toggleStoreBtn').onclick=toggleStore; $('#addRiderBtn').onclick=addRider; $('#saveSettingsBtn').onclick=saveSettings; $$('.tab').forEach(b=>b.onclick=()=>showTab(b.dataset.tab)); $$('.chip').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;$$('.chip').forEach(x=>x.classList.toggle('active',x===b));renderOrders()})}
async function login(){setNotice('');try{await auth.signInWithEmailAndPassword($('#adminEmail').value.trim(),$('#adminPassword').value)}catch(e){setNotice(e.message)}}
async function onAuth(u){user=u;if(!u){$('#loginCard').hidden=false;$('#adminPanel').hidden=true;$('#connectionText').textContent='Logged out';return}$('#connectionText').textContent='Checking admin access...';try{const snap=await db.collection('admins').doc(u.uid).get();adminOk=snap.exists || ['owner','admin'].includes(clean(snap.data()?.role).toLowerCase()); if(!adminOk){setNotice('This account is not added in admins collection. UID: '+u.uid); await auth.signOut(); return}$('#loginCard').hidden=true;$('#adminPanel').hidden=false;$('#adminName').textContent=u.email||'Owner';listen()}catch(e){setNotice('Admin check failed: '+e.message)}}
function listen(){db.collection('store').doc(window.TIFFIN_STORE_ID||'main').onSnapshot(s=>{store=s.data()||{};renderStore()});db.collection('riders').orderBy('updatedAt','desc').onSnapshot(s=>{riders=s.docs.map(d=>({id:d.id,...d.data()}));renderRiders();renderOrders()});db.collection('orders').orderBy('createdAt','desc').limit(100).onSnapshot(s=>{orders=s.docs.map(d=>({id:d.id,...d.data()}));renderOrders();renderStats();$('#connectionText').textContent='Live orders connected'},e=>{$('#connectionText').textContent=e.message})}
function status(o){return clean(o.adminStatus||o.orderStatus||o.deliveryStatus||o.status||'confirmed').toLowerCase().replace(/[\s-]+/g,'_')}
function paid(o){const p=clean(o.paymentStatus||o.payment?.status||o.status).toLowerCase();return ['paid','confirmed','payment_success','success'].includes(p)||o.paidAt||o.paymentId||o.razorpayPaymentId}
function active(o){return paid(o)&&!['delivered','completed','cancelled','canceled'].includes(status(o))}
function renderStats(){let today=new Date();today.setHours(0,0,0,0);let todays=orders.filter(o=>(ts(o.createdAt)||new Date(0))>=today&&paid(o));$('#statToday').textContent=todays.length;$('#statRevenue').textContent=money(todays.reduce((a,o)=>a+Number(o.total||o.totalPaid||o.totals?.total||0),0));$('#statActive').textContent=orders.filter(active).length;$('#statReady').textContent=orders.filter(o=>['ready','prepared','rider_assigned','assigned'].includes(status(o))).length}
function filtered(){return orders.filter(o=>{let s=status(o); if(filter==='all')return paid(o); if(filter==='past')return ['delivered','completed','cancelled','canceled'].includes(s); if(filter==='new')return ['confirmed','received','new','placed','order_placed'].includes(s)&&paid(o); if(filter==='preparing')return ['preparing','accepted','in_kitchen','food_preparing'].includes(s); if(filter==='delivery')return ['ready','prepared','rider_assigned','assigned','picked_up','out_for_delivery','on_the_way','reached_location','reached'].includes(s); return active(o)})}
function itemsHtml(items){items=Array.isArray(items)?items:[];return items.map(i=>`<span class="item-chip">${esc(i.name||i.title||'Item')} × ${esc(i.qty||i.quantity||1)}</span>`).join('')||'<span class="item-chip">Items unavailable</span>'}
function renderOrders(){const list=$('#ordersList');const data=filtered();if(!data.length){list.innerHTML='<div class="empty">No orders in this filter.</div>';return}list.innerHTML=data.map(orderCard).join('');list.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>handleOrderAction(b));list.querySelectorAll('select[data-rider-select]').forEach(s=>s.onchange=()=>assignRider(s.dataset.id,s.value))}
function orderCard(o){let s=status(o), name=o.customerName||o.customer?.name||'Customer', ph=o.customerPhone||o.customer?.phone||'', addr=o.deliveryAddress||o.address||o.deliveryLocation?.fullAddress||'';let rid=o.assignedRiderId||o.riderId||'';let opts='<option value="">Assign rider</option>'+riders.map(r=>`<option value="${esc(r.id)}" ${r.id===rid?'selected':''}>${esc(r.name||r.phone||r.id)} ${r.online?'• online':''}</option>`).join('');return `<article class="order-card"><div class="order-head"><div><div class="order-id">#${esc(o.id)}</div><span class="badge ${active(o)?'green':''}">${esc(label(s))}</span></div><b>${money(o.total||o.totalPaid||o.totals?.total)}</b></div><div class="items">${itemsHtml(o.items)}</div><div class="kv"><span>Customer</span><b>${esc(name)} ${ph?`· ${esc(ph)}`:''}</b><span>Address</span><span>${esc(addr||'No address')}</span><span>Payment</span><span>${esc(o.paymentStatus||'paid')}</span><span>Rider</span><span>${esc(o.assignedRiderName||o.riderName||'Not assigned')}</span></div><div class="actions"><button class="btn soft small" data-action="preparing" data-id="${esc(o.id)}">Preparing</button><button class="btn soft small" data-action="ready" data-id="${esc(o.id)}">Ready</button><select class="select" data-rider-select data-id="${esc(o.id)}">${opts}</select><button class="btn danger small" data-action="cancel" data-id="${esc(o.id)}">Cancel</button></div></article>`}
function label(s){return ({confirmed:'Order received',received:'Order received',preparing:'Preparing',ready:'Ready',rider_assigned:'Rider assigned',assigned:'Rider assigned',picked_up:'Out for delivery',out_for_delivery:'Out for delivery',reached_location:'Reached',delivered:'Delivered',cancelled:'Cancelled'}[s]||s.replace(/_/g,' '))}
function esc(v){return clean(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function byId(id){return orders.find(o=>o.id===id)||{id}}
async function patchOrder(o,patch){patch={...patch,updatedAt:now()};await db.collection('orders').doc(o.id).set(patch,{merge:true});if(o.customerId)await db.collection('customers').doc(o.customerId).collection('orders').doc(o.id).set(patch,{merge:true})}
async function handleOrderAction(btn){let o=byId(btn.dataset.id), a=btn.dataset.action;if(a==='preparing')await patchOrder(o,{status:'preparing',orderStatus:'preparing',adminStatus:'preparing'});if(a==='ready')await patchOrder(o,{status:'ready',orderStatus:'ready',adminStatus:'ready'});if(a==='cancel')await patchOrder(o,{status:'cancelled',orderStatus:'cancelled',adminStatus:'cancelled',cancelledAt:now()})}
async function assignRider(orderId,riderId){let o=byId(orderId);if(!riderId)return;let r=riders.find(x=>x.id===riderId);let patch={status:'rider_assigned',orderStatus:'rider_assigned',adminStatus:'rider_assigned',assignedRiderId:riderId,riderId:riderId,assignedRiderName:r?.name||'',riderName:r?.name||'',assignedRiderPhone:r?.phone||'',riderPhone:r?.phone||'',assignedAt:now()};await patchOrder(o,patch);await db.collection('riders').doc(riderId).set({currentOrderId:orderId,updatedAt:now()},{merge:true})}
function renderRiders(){const list=$('#ridersList');if(!riders.length){list.innerHTML='<div class="empty">No riders yet.</div>';return}list.innerHTML=riders.map(r=>`<div class="rider-card"><div class="order-head"><div><b>${esc(r.name||'Rider')}</b><p class="muted">+91 ${esc(r.phone||'')}</p></div><span class="badge ${r.online?'green':''}">${r.online?'Online':'Offline'}</span></div><div class="kv"><span>Current</span><span>${esc(r.currentOrderId||'-')}</span><span>Last GPS</span><span>${r.location?.lat?`${r.location.lat.toFixed?.(5)||r.location.lat}, ${r.location.lng.toFixed?.(5)||r.location.lng}`:'-'}</span></div></div>`).join('')}
async function addRider(){let name=clean($('#newRiderName').value), phone=phone10($('#newRiderPhone').value);if(!name||phone.length!==10){alert('Enter rider name and 10 digit phone');return}await db.collection('riders').doc(phone).set({name,phone,online:false,createdAt:now(),updatedAt:now()},{merge:true});$('#newRiderName').value='';$('#newRiderPhone').value=''}
function renderStore(){const open=store.open!==false;$('#storeLine').textContent=open?'Store open':'Store closed';$('#toggleStoreBtn').textContent=open?'Close store':'Open store';$('#restaurantAddress').value=store.restaurantLocation?.address||RESTAURANT.address;$('#restaurantLat').value=store.restaurantLocation?.lat||RESTAURANT.lat;$('#restaurantLng').value=store.restaurantLocation?.lng||RESTAURANT.lng}
async function toggleStore(){await db.collection('store').doc(window.TIFFIN_STORE_ID||'main').set({open:!(store.open!==false),updatedAt:now()},{merge:true})}
async function saveSettings(){await db.collection('store').doc(window.TIFFIN_STORE_ID||'main').set({restaurantLocation:{address:$('#restaurantAddress').value,lat:Number($('#restaurantLat').value),lng:Number($('#restaurantLng').value)},updatedAt:now()},{merge:true});alert('Saved')}
function showTab(id){$$('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===id));$$('.tab-panel').forEach(p=>p.classList.toggle('active',p.id===id))}
document.addEventListener('DOMContentLoaded',init);
})();
